name: steps examples

on:
  push:
    branches:
      - main

jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: verification of node version
        run: node --version

  hello_world_job:
    runs-on: ubuntu-latest
    name: Example of custom action
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Hello World Action
        id: step-caller
        run: |
          output=$(./.github/actions/hello)
          echo "::set-output name=random-number::$output"

      - run: echo random-number ${{ steps.step-caller.outputs.random-number }}
        shell: bash
