name: steps examples

on:
  push:
    branches:
      - main

jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
    - name: Configuração do Node.js
      uses: actions/setup-node@v3

    - name: verification of node version
      run: node --version
